{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "74d7aa63",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 启动SAP GUI、连接服务器并执行报表下载\n",
    "import os\n",
    "import subprocess\n",
    "import time\n",
    "import win32com.client\n",
    "import sys\n",
    "\n",
    "# 强制关闭 Excel 的函数\n",
    "def close_excel():\n",
    "    \"\"\"强制关闭所有 Excel 进程\"\"\"\n",
    "    try:\n",
    "        result = subprocess.run(\n",
    "            [\"taskkill\", \"/F\", \"/IM\", \"EXCEL.EXE\"],\n",
    "            capture_output=True,\n",
    "            timeout=5,\n",
    "            text=True\n",
    "        )\n",
    "        if \"成功\" in result.stdout or \"SUCCESS\" in result.stdout:\n",
    "            print(\"✓ 已关闭 Excel\")\n",
    "            return True\n",
    "        elif \"找不到\" in result.stdout or \"not found\" in result.stdout.lower():\n",
    "            print(\"✓ Excel 未运行\")\n",
    "            return True\n",
    "        else:\n",
    "            return False\n",
    "    except Exception as e:\n",
    "        print(f\"⚠ 关闭 Excel 时出错: {e}\")\n",
    "        return False\n",
    "\n",
    "# 多个可能的SAP GUI路径\n",
    "sap_paths = [\n",
    "    r\"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\SAP Front End\\SAP Logon Pad.lnk\",\n",
    "    r\"C:\\Program Files (x86)\\SAP\\FrontEnd\\SAPgui\\saplogon.exe\",\n",
    "    r\"C:\\Program Files\\SAP\\FrontEnd\\SAPgui\\saplogon.exe\",\n",
    "    r\"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\SAP Front End.sap\",\n",
    "]\n",
    "\n",
    "try:\n",
    "    # 检查SAP GUI是否已经运行\n",
    "    try:\n",
    "        SapGuiAuto = win32com.client.GetObject(\"SAPGUI\")\n",
    "        print(\"✓ SAP GUI 已在运行\")\n",
    "    except:\n",
    "        print(\"SAP GUI 未运行，正在查找启动文件...\")\n",
    "        \n",
    "        # 尝试每个路径\n",
    "        found = False\n",
    "        for sap_path in sap_paths:\n",
    "            if os.path.exists(sap_path):\n",
    "                print(f\"找到: {sap_path}\")\n",
    "                print(\"正在启动 SAP GUI...\")\n",
    "                subprocess.Popen([sap_path], shell=True)\n",
    "                print(\"SAP GUI 正在启动...\")\n",
    "                time.sleep(5)\n",
    "                found = True\n",
    "                break\n",
    "        \n",
    "        if not found:\n",
    "            print(\"✗ 未找到SAP GUI启动文件\")\n",
    "            print(\"\\n已尝试以下路径:\")\n",
    "            for path in sap_paths:\n",
    "                print(f\"  - {path}\")\n",
    "            print(\"\\n请手动启动SAP GUI并登录\")\n",
    "            sys.exit(1)\n",
    "        \n",
    "        # 重新获取SAP GUI对象\n",
    "        try:\n",
    "            SapGuiAuto = win32com.client.GetObject(\"SAPGUI\")\n",
    "        except:\n",
    "            print(\"✗ SAP GUI 启动失败\")\n",
    "            sys.exit(1)\n",
    "    \n",
    "    # 检查是否已有连接\n",
    "    application = SapGuiAuto.GetScriptingEngine\n",
    "    \n",
    "    if application.Children.Count > 0:\n",
    "        connection = application.Children(0)\n",
    "        if connection.Children.Count > 0:\n",
    "            session = connection.Children(0)\n",
    "            print(f\"✓ 已登录 - 用户: {session.Info.User}, 系统: {session.Info.SystemName}\")\n",
    "        else:\n",
    "            print(\"⚠ 有连接但未登录，请手动登录\")\n",
    "            sys.exit(1)\n",
    "    else:\n",
    "        print(\"\\n正在连接到 RPR - ECC Production 服务器...\")\n",
    "        \n",
    "        # 获取SAP Logon窗口并连接\n",
    "        try:\n",
    "            connection = application.OpenConnection(\"RPR - ECC Production\", True)\n",
    "            print(\"✓ 已发起连接到 RPR - ECC Production\")\n",
    "            print(\"请在弹出的登录窗口中输入用户名和密码...\")\n",
    "            \n",
    "            # 等待用户登录（最多等待60秒）\n",
    "            for i in range(60):\n",
    "                time.sleep(1)\n",
    "                if connection.Children.Count > 0:\n",
    "                    session = connection.Children(0)\n",
    "                    print(f\"\\n✓✓✓ 登录成功！\")\n",
    "                    print(f\"用户: {session.Info.User}\")\n",
    "                    print(f\"系统: {session.Info.SystemName}\")\n",
    "                    print(f\"客户端: {session.Info.Client}\")\n",
    "                    break\n",
    "                if (i + 1) % 10 == 0:\n",
    "                    print(f\"等待登录中... ({i + 1}秒)\")\n",
    "            else:\n",
    "                print(\"⚠ 等待超时，请手动登录后重新运行\")\n",
    "                sys.exit(1)\n",
    "                \n",
    "        except Exception as e:\n",
    "            print(f\"✗ 连接服务器失败: {e}\")\n",
    "            print(\"\\n请手动操作：\")\n",
    "            print(\"1. 在SAP Logon窗口中双击 'RPR - ECC Production'\")\n",
    "            print(\"2. 输入用户名和密码登录\")\n",
    "            sys.exit(1)\n",
    "    \n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"开始执行报表下载自动化\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    # 最大化窗口\n",
    "    session.findById(\"wnd[0]\").maximize()\n",
    "    time.sleep(0.5)\n",
    "    print(\"✓ 窗口已最大化\")\n",
    "    \n",
    "    # 在命令栏输入事务代码 S_ALR_87011990\n",
    "    session.findById(\"wnd[0]/tbar[0]/okcd\").text = \"S_ALR_87011990\"\n",
    "    session.findById(\"wnd[0]\").sendVKey(0)  # 按回车键执行\n",
    "    time.sleep(3)\n",
    "    print(\"✓ 已进入事务代码 S_ALR_87011990\")\n",
    "    \n",
    "    # 定义要下载的报表列表\n",
    "    reports = [\n",
    "        {\"variant\": \"Z025_01\", \"filename\": \"SAP_FA LIST_01_Z025\"},\n",
    "        {\"variant\": \"Z025_05\", \"filename\": \"SAP_FA LIST_05_Z025\"},\n",
    "        {\"variant\": \"ZTXT_05\", \"filename\": \"SAP_FA LIST_05_ZTXT\"},\n",
    "        {\"variant\": \"Z233_05\", \"filename\": \"SAP_FA LIST_05_Z233\"},\n",
    "        {\"variant\": \"Z503_05\", \"filename\": \"SAP_FA LIST_05_Z503\"}\n",
    "    ]\n",
    "    \n",
    "    # 循环下载每个报表\n",
    "    for idx, report in enumerate(reports, 1):\n",
    "        print(f\"\\n{'='*60}\")\n",
    "        print(f\"开始下载第 {idx} 个报表: {report['variant']}\")\n",
    "        print(f\"{'='*60}\")\n",
    "        \n",
    "        # 尝试多种方式输入报表名称\n",
    "        input_success = False\n",
    "        \n",
    "        # 尝试1: 在选择屏幕直接输入\n",
    "        try:\n",
    "            session.findById(\"wnd[0]/usr/ctxtPA_VARI\").text = report['variant']\n",
    "            time.sleep(0.5)\n",
    "            print(f\"✓ 已输入变式 {report['variant']}\")\n",
    "            input_success = True\n",
    "        except Exception as e1:\n",
    "            print(f\"尝试1失败: 未找到变式输入框\")\n",
    "        \n",
    "        # 尝试2: 通过F4帮助选择\n",
    "        if not input_success:\n",
    "            try:\n",
    "                # 点击变式帮助按钮\n",
    "                session.findById(\"wnd[0]/tbar[1]/btn[17]\").press()\n",
    "                time.sleep(1)\n",
    "                \n",
    "                # 在弹出窗口输入\n",
    "                session.findById(\"wnd[1]/usr/txtV-LOW\").text = report['variant']\n",
    "                session.findById(\"wnd[1]/usr/txtV-LOW\").caretPosition = 7\n",
    "                time.sleep(0.5)\n",
    "                print(f\"✓ 已在弹出窗口输入 {report['variant']}\")\n",
    "                \n",
    "                # 确认选择\n",
    "                session.findById(\"wnd[1]/tbar[0]/btn[8]\").press()\n",
    "                time.sleep(1.5)\n",
    "                print(\"✓ 已确认选择\")\n",
    "                input_success = True\n",
    "            except Exception as e2:\n",
    "                print(f\"尝试2失败: {e2}\")\n",
    "        \n",
    "        # 尝试3: 直接执行（如果已有默认变式）\n",
    "        if not input_success:\n",
    "            print(\"⚠ 无法输入报表名称，尝试直接执行...\")\n",
    "            time.sleep(0.5)\n",
    "        \n",
    "        # 设置日期为当月最后一天\n",
    "        from datetime import datetime\n",
    "        from calendar import monthrange\n",
    "        \n",
    "        # 获取当前年月和月末日期\n",
    "        now = datetime.now()\n",
    "        year = now.year\n",
    "        month = now.month\n",
    "        last_day = monthrange(year, month)[1]\n",
    "        end_date = f\"{month:02d}/{last_day:02d}/{year:04d}\"\n",
    "        end_date_formatted = f\"{month:02d}/{last_day:02d}/{year:04d}\"  # SAP 日期格式\n",
    "        \n",
    "        print(f\"正在设置日期为当月最后一天: {end_date_formatted}\")\n",
    "        \n",
    "        date_set_success = False\n",
    "        \n",
    "        # 方法1: 直接输入日期文本（最简单）\n",
    "        try:\n",
    "            session.findById(\"wnd[0]/usr/ctxtBERDATUM\").text = end_date_formatted\n",
    "            time.sleep(0.3)\n",
    "            print(f\"✓ 已设置日期为: {end_date_formatted} (方法1: 直接输入)\")\n",
    "            date_set_success = True\n",
    "        except:\n",
    "            pass  # 静默失败，尝试下一个方法\n",
    "        \n",
    "        # 方法2: 尝试其他可能的日期字段 ID\n",
    "        if not date_set_success:\n",
    "            try:\n",
    "                session.findById(\"wnd[0]/usr/ctxtPA_STIDA\").text = end_date_formatted\n",
    "                time.sleep(0.3)\n",
    "                print(f\"✓ 已设置日期为: {end_date_formatted} (方法2: PA_STIDA)\")\n",
    "                date_set_success = True\n",
    "            except:\n",
    "                pass  # 静默失败，尝试下一个方法\n",
    "        \n",
    "        # 方法3: 通过日历控件选择\n",
    "        if not date_set_success:\n",
    "            try:\n",
    "                # 设置焦点到日期字段\n",
    "                session.findById(\"wnd[0]/usr/ctxtBERDATUM\").setFocus()\n",
    "                session.findById(\"wnd[0]/usr/ctxtBERDATUM\").caretPosition = 10\n",
    "                \n",
    "                # 打开日期选择器（F4键）\n",
    "                session.findById(\"wnd[0]\").sendVKey(4)\n",
    "                time.sleep(0.5)\n",
    "                \n",
    "                # 在日历控件中选择日期\n",
    "                session.findById(\"wnd[1]/usr/cntlCONTAINER/shellcont/shell\").focusDate = end_date\n",
    "                session.findById(\"wnd[1]/usr/cntlCONTAINER/shellcont/shell\").selectionInterval = f\"{end_date},{end_date}\"\n",
    "                time.sleep(0.5)\n",
    "                \n",
    "                # 确认日期选择\n",
    "                session.findById(\"wnd[1]/tbar[0]/btn[0]\").press()\n",
    "                time.sleep(0.5)\n",
    "                \n",
    "                print(f\"✓ 已设置日期为: {end_date_formatted} (方法3: 日历控件)\")\n",
    "                date_set_success = True\n",
    "            except:\n",
    "                pass  # 静默失败\n",
    "        \n",
    "        # 如果所有方法都失败\n",
    "        if not date_set_success:\n",
    "            print(f\"ℹ 未找到日期字段，将使用变式中保存的默认日期\")\n",
    "            print(f\"  变式 {report['variant']} 应已包含正确的日期参数\")\n",
    "        \n",
    "        time.sleep(0.5)\n",
    "        \n",
    "        # 执行报表\n",
    "        session.findById(\"wnd[0]/tbar[1]/btn[8]\").press()\n",
    "        time.sleep(3)\n",
    "        print(\"✓ 报表正在执行...\")\n",
    "        \n",
    "        # 选择导出菜单\n",
    "        session.findById(\"wnd[0]/mbar/menu[0]/menu[1]/menu[1]\").select()\n",
    "        time.sleep(1)\n",
    "        print(\"✓ 已打开导出菜单\")\n",
    "        \n",
    "        # 设置文件名\n",
    "        session.findById(\"wnd[1]/usr/subSUB_CONFIGURATION:SAPLSALV_GUI_CUL_EXPORT_AS:0512/txtGS_EXPORT-FILE_NAME\").text = report['filename']\n",
    "        session.findById(\"wnd[1]/usr/subSUB_CONFIGURATION:SAPLSALV_GUI_CUL_EXPORT_AS:0512/txtGS_EXPORT-FILE_NAME\").caretPosition = len(report['filename'])\n",
    "        time.sleep(0.5)\n",
    "        print(f\"✓ 已设置文件名: {report['filename']}\")\n",
    "        \n",
    "        # 继续\n",
    "        session.findById(\"wnd[1]/tbar[0]/btn[20]\").press()\n",
    "        time.sleep(1)\n",
    "        \n",
    "        # 设置保存路径\n",
    "        session.findById(\"wnd[1]/usr/ctxtDY_PATH\").setFocus()\n",
    "        session.findById(\"wnd[1]/usr/ctxtDY_PATH\").caretPosition = 0\n",
    "        session.findById(\"wnd[1]\").sendVKey(4)  # F4 帮助\n",
    "        time.sleep(0.5)\n",
    "        \n",
    "        # 根据当前月份动态生成路径\n",
    "        month_mapping = {\n",
    "            11: \"02 November\",\n",
    "            12: \"03 December\",\n",
    "            1: \"04 January\",\n",
    "            2: \"05 February\",\n",
    "            3: \"06 March\",\n",
    "            4: \"07 April\",\n",
    "            5: \"08 May\",\n",
    "            6: \"09 June\",\n",
    "            7: \"10 July\",\n",
    "            8: \"11 August\",\n",
    "            9: \"12 September\"\n",
    "        }\n",
    "        \n",
    "        current_month = datetime.now().month\n",
    "        month_folder = month_mapping.get(current_month, f\"{current_month:02d} Month\")\n",
    "        year_month_str = datetime.now().strftime(\"%Y%m\")\n",
    "        \n",
    "        # 输入目标路径\n",
    "        save_path = rf\"\\\\apac.wdpr.disney.com\\Corp\\CNKC\\Finance\\Controllership\\FINANCIAL REPORTING\\FY_ 2026\\Month-End\\{month_folder}\\FA Ledger\\Report\\SAP report {year_month_str}\"\n",
    "        session.findById(\"wnd[2]/usr/ctxtDY_PATH\").text = save_path\n",
    "        session.findById(\"wnd[2]/usr/ctxtDY_PATH\").setFocus()\n",
    "        session.findById(\"wnd[2]/usr/ctxtDY_PATH\").caretPosition = len(save_path)\n",
    "        time.sleep(0.5)\n",
    "        print(f\"✓ 已设置保存路径: {month_folder}\")\n",
    "        \n",
    "        # 关闭路径选择窗口\n",
    "        session.findById(\"wnd[2]/tbar[0]/btn[0]\").press()\n",
    "        time.sleep(0.5)\n",
    "        print(f\"保存位置: {save_path}\\\\{report['filename']}.xlsx\")\n",
    "        # 设置\"不替换\"选项（防止 Excel 自动打开）\n",
    "        try:\n",
    "            # 取消勾选\"用合适的应用程序打开\"复选框\n",
    "            session.findById(\"wnd[1]/usr/chxDY_NO_REPLACE\").selected = True\n",
    "            print(\"✓ 已设置为后台保存模式（不打开 Excel）\")\n",
    "        except:\n",
    "            try:\n",
    "                # 另一种可能的ID\n",
    "                session.findById(\"wnd[1]/usr/ctxtDY_NO_REPLACE\").selected = True\n",
    "                print(\"✓ 已设置为后台保存模式（不打开 Excel）\")\n",
    "            except:\n",
    "                print(\"⚠ 无法找到后台保存选项，文件可能会自动打开\")\n",
    "        \n",
    "        time.sleep(0.5)\n",
    "        \n",
    "        # 确认保存，同时开始监控 Excel\n",
    "        session.findById(\"wnd[1]/tbar[0]/btn[11]\").press()  # 点击\"生成\"按钮\n",
    "        \n",
    "        print(f\"\\n✓✓✓ 第 {idx} 个报表已开始导出...\")\n",
    "        print(f\"保存位置: \\\\\\\\apac.wdpr.disney.com\\\\Corp\\\\CNKC\\\\Finance\\\\Controllership\\\\FINANCIAL REPORTING\\\\FY_ 2026\\\\Month-End\\\\02 November\\\\FA Ledger\\\\Report\\\\SAP report 202511\\\\{report['filename']}.xlsx\")\n",
    "        \n",
    "        # 等待文件保存完成\n",
    "        time.sleep(3)\n",
    "        \n",
    "        # 关闭所有 SAP 弹出窗口\n",
    "        try:\n",
    "            while session.Children.Count > 1:\n",
    "                session.findById(\"wnd[1]\").close()\n",
    "                time.sleep(0.3)\n",
    "        except:\n",
    "            pass\n",
    "    \n",
    "        # 返回到事务代码选择屏幕\n",
    "        try:\n",
    "            session.findById(\"wnd[0]/tbar[0]/btn[3]\").press()  # 按返回按钮\n",
    "            time.sleep(0.5)\n",
    "            print(\"✓ 已返回到 S_ALR_87011990 选择屏幕\")\n",
    "        except:\n",
    "            print(\"⚠ 无法返回选择屏幕\")\n",
    "        \n",
    "        # 每个报表完成后，关闭可能打开的 Excel\n",
    "        print(f\"\\n第 {idx} 个报表完成，检查并关闭 Excel...\")\n",
    "        close_excel()\n",
    "        time.sleep(1)\n",
    "        \n",
    "        # 如果不是最后一个报表，提示准备下一个\n",
    "        if idx < len(reports):\n",
    "            print(f\"准备下载下一个报表...\")\n",
    "            time.sleep(1)\n",
    "        \n",
    "    \n",
    "    print(f\"\\n{'='*60}\")\n",
    "    print(f\"✓✓✓ 所有任务完成！共下载了 {len(reports)} 个报表\")\n",
    "    print(f\"{'='*60}\")\n",
    "    \n",
    "except Exception as e:\n",
    "    print(f\"\\n✗ 发生错误: {e}\")\n",
    "    print(f\"错误类型: {type(e).__name__}\")\n",
    "    import traceback\n",
    "    print(\"\\n详细错误信息:\")\n",
    "    traceback.print_exc()\n",
    " "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
